GET http://localhost:3000/notes

###

GET http://localhost:3000/notes/3

###

POST http://localhost:3000/notes
Content-Type: application/json

{
  "title": "Note 1",
  "content": "Content 1"
}

###

PUT http://localhost:3000/notes/1
Content-Type: application/json

{
  "title": "Note 2",
  "content": "Content 2"
}

###

DELETE http://localhost:3000/notes/1

###

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6Impvc3VhIiwiZW1haWwiOiJqb3N1YUB0ZXMuY29tIiwiZ2VuZGVyIjoiTWFsZSIsInRhbmdnYWxfZGlidWF0IjoiMjAyNS0wNS0yMVQxMzoxMDoxMy4wMDBaIiwidGFuZ2dhbF9kaXViYWgiOiIyMDI1LTA1LTIxVDE2OjMyOjI1LjAwMFoiLCJpYXQiOjE3NDc4Nzk1NTYsImV4cCI6MTc0Nzg3OTU4Nn0.QKkqeWK_Bd5mPBuehQmgMnkgr2pPekP8x720CnrCrHs

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "josua@tes.com",
    "password": "jos"
}

###

POST http://localhost:3000/register 
Content-Type: application/json

{
    "name": "josua",
    "email": "josua@tes.com",
    "gender": "Male",
    "password": "jos"
}

###

DELETE http://localhost:3000/delete-user/4

###